### ISSUE TITLE
Simpler way to override or unregister items

### ISSUE THREAD

**Issue by Prim69** [df-mc/dragonfly#467] opened 2022-04-02 15:29 UTC
Currently the only way to have a custom item is to only give that item to players, which works but the original item is still in the creative inventory. 
Another method is to override it in HandleItemUse but thats not convenient.

I think the best solution would be a way to unregister items

**Comment by T14Raptor** [comment] 2022-04-02 15:30
Duplicate of #221?

**Comment by Sandertv** [comment] 2022-04-02 15:33
I've mentioned this before, I'm not a fan of replacing (let alone unregistering!) items and blocks. All dragonfly code assumes specific items and blocks exist and being able to remove items/blocks opens up a massive can of worms.

**Closed by Sandertv** 2022-04-02 15:33 UTC
