### ISSUE TITLE
Stored player direction is wrong

### ISSUE THREAD

**Issue by JustTalDevelops** [df-mc/dragonfly#452] opened 2022-03-15 23:35 UTC
You can test this by joining, facing a direction, and then rejoining. Your player will be facing a different direction.

**Comment by Sandertv** [comment] 2022-03-22 20:27
@JustTalDevelops are you able to debug if this is because of an error in the data saving/loading or just the client itself being weird?

**Comment by JustTalDevelops** [comment] 2022-03-22 22:22
I am pretty positive this is an issue with Dragonfly - using a custom provider and setting a direction seems to work fine consistently.

**Comment by Sandertv** [comment] 2022-03-22 22:25
That is weird. I just can't seem to find anything wrong with the way yaw/pitch is loaded or stored 🤔

**Comment by T14Raptor** [comment] 2022-03-22 22:27
Is the different direction consistent?

**Comment by Sandertv** [comment] 2022-03-27 10:11
@JustTalDevelops ^

**Comment by JustTalDevelops** [comment] 2022-03-27 18:59
What exactly do you mean by that?

**Comment by Sandertv** [comment] 2022-05-05 12:45
I'm unable to reproduce this. Could you make sure this happens with a vanilla dragonfly server?

**Comment by unickorn** [comment] 2022-11-23 17:32
I also cannot reproduce this, maybe close it at this point unless Tal has something to add?

**Comment by JustTalDevelops** [comment] 2022-11-24 21:40
No, this still seems to be happening. Just tested on latest commit.

**Comment by Sandertv** [comment] 2024-12-15 21:15
This appears to be fixed since entity transactions.

**Closed by Sandertv** 2024-12-15 21:15 UTC
Labels: bug
