### ISSUE TITLE
Implement cursor inventory API

### ISSUE THREAD

**Issue by ItsZodiaX** [df-mc/dragonfly#715] opened 2022-12-21 03:43 UTC
There is no way to clear the item that the player is holding on the cursor inv right now.
It needed it in [my case](https://youtu.be/ya9R5sZvO8Y) (It isn't actually a dupe glitch like the video title).
The player was holding an item in cursor inv and paste it back to inv when kit reapplied (Items added).

**Comment by T14Raptor** [comment] 2022-12-21 04:21
Duplicate of #510

**Closed by T14Raptor** 2022-12-21 04:21 UTC
