### ISSUE TITLE
Ghost Block Appears

### ISSUE THREAD

**Issue by Mohamed587100** [df-mc/dragonfly#386] opened 2022-01-03 02:07 UTC
OS: MacOS Big Sur

dragonfly: 614691ae18ddbcf96a6ed41171a6c7758c7561a9

go: go version go1.17.5 darwin/amd64

Hard to Express, There is a video and a demo code patch for the latest master commit

At the end of video, I rejoin the server and then ghost block disappears. I express that to avoid misunderstood the action.

Video: https://streamable.com/xkrzpq

Sorry for my bad English.

```patch
diff --git a/main.go b/main.go
index 1ea18b4..ed9ba85 100644
--- a/main.go
+++ b/main.go
@@ -3,7 +3,13 @@ package main
 import (
 	"fmt"
 	"github.com/df-mc/dragonfly/server"
+	"github.com/df-mc/dragonfly/server/block/cube"
+	"github.com/df-mc/dragonfly/server/event"
+	"github.com/df-mc/dragonfly/server/player"
 	"github.com/df-mc/dragonfly/server/player/chat"
+	"github.com/df-mc/dragonfly/server/world"
+	"github.com/df-mc/dragonfly/server/world/particle"
+	"github.com/go-gl/mathgl/mgl64"
 	"github.com/pelletier/go-toml"
 	"github.com/sirupsen/logrus"
 	"io/ioutil"
@@ -29,8 +35,10 @@ func main() {
 	}
 
 	for {
-		if _, err := srv.Accept(); err != nil {
+		if p, err := srv.Accept(); err != nil {
 			return
+		} else {
+			p.Handle(&Handler{player: p})
 		}
 	}
 }
@@ -57,3 +65,20 @@ func readConfig() (server.Config, error) {
 	}
 	return c, nil
 }
+
+type Handler struct {
+	player.NopHandler
+	player *player.Player
+}
+
+func (h Handler) HandleMove(ctx *event.Context, newPos mgl64.Vec3, _ float64, _ float64) {
+	blockPos := newPos.Add(mgl64.Vec3{0, -1, 0})
+	h.player.SendPopup(fmt.Sprintf("You are standing on %T", h.player.World().Block(cube.PosFromVec3(blockPos))))
+	h.player.World().AddParticle(blockPos, particle.BlockForceField{})
+}
+
+func (h Handler) HandleBlockPlace(ctx *event.Context, pos cube.Pos, b world.Block) {
+	ctx.After(func(c bool) {
+		h.player.World().BreakBlock(pos)
+	})
+}

```

**Comment by RestartFU** [comment] 2022-01-03 05:19
when standing on those ghost blocks, the popup sent says that you're in the air, I believe this is a client issue, because you were placing and removing blocks so fast.

**Comment by Mohamed587100** [comment] 2022-01-03 09:01
> when standing on those ghost blocks, the popup sent says that you're in the air, so the server thinks you're in the air, I believe this is a client issue, because you were placing and removing blocks so fast. And don't worry, your English is good

but never happen in PM or NK

**Comment by Sandertv** [comment] 2022-01-03 11:29
Could you please try dfe42125ea297255ad9b95807856d68c18b32585 and see if it is fixed with that commit?

**Comment by Mohamed587100** [comment] 2022-01-03 12:45
> Could you please try [dfe4212](https://github.com/df-mc/dragonfly/commit/dfe42125ea297255ad9b95807856d68c18b32585) and see if it is fixed with that commit?

OMG fixed thank you very much

**Comment by Mohamed587100** [comment] 2022-01-03 22:58
after "fix", when you click the ghost block, the ghost block disappear.
new video and code is uploading...

**Comment by Mohamed587100** [comment] 2022-01-03 23:02
https://streamable.com/jrcxak

**Comment by Mohamed587100** [comment] 2022-01-03 23:03
```patch
diff --git a/main.go b/main.go
index 1ea18b4..29d2e19 100644
--- a/main.go
+++ b/main.go
@@ -3,11 +3,28 @@ package main
 import (
 	"fmt"
 	"github.com/df-mc/dragonfly/server"
+	"github.com/df-mc/dragonfly/server/block"
+	"github.com/df-mc/dragonfly/server/block/cube"
+	"github.com/df-mc/dragonfly/server/entity"
+	"github.com/df-mc/dragonfly/server/entity/damage"
+	"github.com/df-mc/dragonfly/server/event"
+	"github.com/df-mc/dragonfly/server/item"
+	"github.com/df-mc/dragonfly/server/player"
 	"github.com/df-mc/dragonfly/server/player/chat"
+	"github.com/df-mc/dragonfly/server/world"
+	"github.com/df-mc/dragonfly/server/world/particle"
+	"github.com/df-mc/dragonfly/server/world/sound"
+	"github.com/go-gl/mathgl/mgl64"
 	"github.com/pelletier/go-toml"
+	"github.com/sandertv/gophertunnel/minecraft/text"
 	"github.com/sirupsen/logrus"
 	"io/ioutil"
+	"math"
+	"math/rand"
 	"os"
+	"strconv"
+	"strings"
+	"time"
 )
 
 func main() {
@@ -29,8 +46,10 @@ func main() {
 	}
 
 	for {
-		if _, err := srv.Accept(); err != nil {
+		if p, err := srv.Accept(); err != nil {
 			return
+		} else {
+			p.Handle(NewHandler(p))
 		}
 	}
 }
@@ -57,3 +76,185 @@ func readConfig() (server.Config, error) {
 	}
 	return c, nil
 }
+
+func cubePosHash(pos cube.Pos) string {
+	x := int64(pos[0])
+	y := int64(pos[1])
+	z := int64(pos[2])
+	toString := strconv.FormatInt
+	return strings.Join([]string{toString(x, 10), toString(y, 10), toString(z, 10)}, ",")
+}
+
+func getAttackPosDelta(pos mgl64.Vec3, yaw, pitch float64) mgl64.Vec3 {
+	ran := 90 + rand.Float64()*30 - 15
+	newZ := pos.Z() + 3.0*math.Sin(rad(yaw+ran))
+	newX := pos.X() + 3.0*math.Cos(rad(yaw+ran))
+	return mgl64.Vec3{newX - pos.X(), 0.0, newZ - pos.Z()}
+}
+
+func rad(f float64) float64 {
+	return f * (math.Pi / 180)
+}
+
+type PlayerHandler struct {
+	player.NopHandler
+	Player   *player.Player
+	lastChat time.Time
+	blockMap map[string]cube.Pos
+	spawn    mgl64.Vec3
+	execDur  time.Time
+}
+
+func (*PlayerHandler) HandleItemDrop(ctx *event.Context, _ *entity.Item) {
+	ctx.Cancel()
+}
+
+func (h *PlayerHandler) HandleFoodLoss(ctx *event.Context, _ int, _ int) {
+	ctx.Cancel()
+}
+
+func (h *PlayerHandler) HandleItemDamage(ctx *event.Context, _ item.Stack, _ int) {
+	ctx.Cancel()
+}
+
+func (h *PlayerHandler) HandleQuit() {
+	logrus.WithField("player", h.Player.Name()).Info("Player quit")
+	h.reset()
+}
+
+func (h *PlayerHandler) HandleAttackEntity(_ *event.Context, _ world.Entity, xkb, ykb *float64, _ *bool) {
+	*xkb, *ykb = 0.4, 0.4
+}
+
+func (h *PlayerHandler) HandleHurt(_ *event.Context, damage *float64, _ damage.Source) {
+	*damage = 0
+}
+
+func (h *PlayerHandler) HandleChat(ctx *event.Context, _ *string) {
+	if h.lastChat.Add(time.Second * 2).After(time.Now()) {
+		ctx.Cancel()
+		h.Player.Messagef(text.Colourf("<red>Chat cooldown</red>"))
+	} else {
+		h.lastChat = time.Now()
+	}
+}
+
+func (h *PlayerHandler) HandleMove(ctx *event.Context, newPos mgl64.Vec3, newYaw, newPitch float64) {
+	if h.Player.GameMode() != world.GameModeCreative {
+		if !time.Now().After(h.execDur) {
+			return
+		}
+		ctx.After(func(c bool) {
+			spawn := h.spawn
+			if math.Abs(newPos.Y()-spawn.Y()) >= 10 {
+				h.reset()
+				return
+			}
+			b := h.Player.World().Block(cube.PosFromVec3(newPos).Side(cube.FaceDown))
+			m := true
+			switch bl := b.(type) {
+			case block.DiamondBlock:
+				ws := h.Player.World().Spawn()
+				h.spawn = ws.Vec3Centre()
+				h.Player.SendPopup(text.Colourf("<blue>Go Lobby!!!</blue>"))
+				h.reset()
+			case block.EmeraldBlock:
+				h.spawn = newPos
+				h.Player.SendPopup(text.Colourf("<green>Spawn Point!!!</green>"))
+				h.clearBlocks()
+			case block.GoldBlock:
+				h.Player.SendPopup(text.Colourf("<gold>Get Score!!!</gold>"))
+				h.reset()
+			case block.Melon:
+				h.Player.World()
+				v := getAttackPosDelta(newPos, newYaw, newPitch)
+				from := newPos.Add(v)
+				from[1] += 1.2
+				vel := from.Sub(newPos).Normalize().Mul(-1.25)
+				vel[1] = 0.45
+				go func() {
+					time.Sleep((time.Second / 20) * 7)
+					h.Player.SetVelocity(vel)
+					h.Player.PlaySound(sound.Explosion{})
+					h.Player.SendPopup(text.Colourf("<bold><green>Knock!!!</green></bold>"))
+				}()
+			default:
+				m = false
+				//FFS
+				bl.Hash()
+			}
+			if m {
+				defer func() {
+					h.execDur = time.Now().Add(time.Second / 2)
+				}()
+			}
+		})
+	}
+}
+
+func (h *PlayerHandler) HandleBlockPlace(ctx *event.Context, pos cube.Pos, _ world.Block) {
+	ctx.After(func(c bool) {
+		if !c {
+			if h.Player.GameMode() != world.GameModeCreative {
+				h.blockMap[cubePosHash(pos)] = pos
+			}
+		}
+	})
+}
+
+func (h *PlayerHandler) HandleBlockBreak(ctx *event.Context, pos cube.Pos, _ *[]item.Stack) {
+	if h.Player.GameMode() != world.GameModeCreative {
+		hash := cubePosHash(pos)
+		if _, ok := h.blockMap[hash]; !ok {
+			ctx.Cancel()
+		} else {
+			delete(h.blockMap, hash)
+		}
+	}
+	ctx.After(func(cancelled bool) {
+		if cancelled {
+			h.Player.World().AddParticle(pos.Vec3Centre(), particle.BlockForceField{})
+		}
+	})
+}
+
+func (h *PlayerHandler) reset() {
+	h.Player.Teleport(h.spawn)
+	h.giveItems()
+	h.clearBlocks()
+}
+
+func (h *PlayerHandler) resetHealth() {
+	h.Player.Heal(h.Player.MaxHealth(), nil)
+}
+
+func (h *PlayerHandler) clearBlocks() {
+	w := h.Player.World()
+	for _, p := range h.blockMap {
+		w.BreakBlock(p)
+	}
+	h.blockMap = make(map[string]cube.Pos)
+}
+
+func (h *PlayerHandler) giveItems() {
+	h.Player.Inventory().Clear()
+	sandstone, _ := world.ItemByName("minecraft:sandstone", 0)
+	_, _ = h.Player.Inventory().AddItem(item.NewStack(sandstone, 64))
+	p, _ := world.ItemByName("minecraft:diamond_pickaxe", 0)
+	_, _ = h.Player.Inventory().AddItem(item.NewStack(p, 1))
+}
+
+func NewHandler(p *player.Player) *PlayerHandler {
+	spawn := p.World().Spawn()
+	h := &PlayerHandler{
+		NopHandler: player.NopHandler{},
+		Player:     p,
+		lastChat:   time.Now(),
+		spawn:      spawn.Vec3Centre().Add(mgl64.Vec3{0, 0.5, 0}),
+		execDur:    time.Now().Add(-time.Second),
+		blockMap:   make(map[string]cube.Pos),
+	}
+	h.reset()
+	p.SetGameMode(world.GameModeSurvival)
+	return h
+}

```

**Comment by Mohamed587100** [comment] 2022-01-04 01:08
the ghost block wasn't place properly in df, but in client it placed, so i think there must be faults in logic just like race condition(maybe not, i am not similar to dragonfly).

**Comment by Sandertv** [comment] 2022-01-05 12:27
Just to be clear, in that video, those blocks aren't supposed to disappear at 0:02 and 0:08 right?

**Comment by Mohamed587100** [comment] 2022-01-05 12:33
> Just to be clear, in that video, those blocks aren't supposed to disappear at 0:02 and 0:08 right?

yes

**Comment by Sandertv** [comment] 2022-01-05 12:35
Yes as in, they're not supposed to disappear? That means there'd be something wrong with block placement logic.

**Comment by Mohamed587100** [comment] 2022-01-05 12:38
> Yes as in, they're not supposed to disappear? That means there'd be something wrong with block placement logic.

yes

**Comment by Blackjack200** [comment] 2022-01-05 14:07
https://streamable.com/vnt0lh

**Comment by Sandertv** [comment] 2022-01-14 18:03
Could you please try 3f677d1e0f28cc560899b054f04dacb7fc850d20 and see if that still happens @Blackjack200?

**Comment by Blackjack200** [comment] 2022-01-21 01:07
still appear

**Comment by JustTalDevelops** [comment] 2022-07-20 00:16
Have you tested this with a recent version of Dragonfly? Using the same code that you provided with the latest commit, I could not reproduce the issue, even while using an autoclicker at 50ms.

**Comment by JustTalDevelops** [comment] 2022-07-20 00:30
@Blackjack200 @Mohamed587100 Can one of you please test it under the latest commit?

**Comment by JustTalDevelops** [comment] 2022-07-25 16:11
Going to mark this as resolved as I cannot reproduce anymore on the latest commit, and I haven't gotten a response from any reporters.

**Closed by JustTalDevelops** 2022-07-25 16:11 UTC
Labels: bug
