### ISSUE TITLE
Explosions pass through liquids

### ISSUE THREAD

**Issue by DaPigGuy** [df-mc/dragonfly#612] opened 2022-07-31 11:35 UTC

**Comment by JustTalDevelops** [comment] 2022-08-01 02:33
How did you test this? I cannot reproduce

**Comment by JustTalDevelops** [comment] 2022-08-01 04:36
This is because liquids such as water and Bedrock don't have blast resistance - though we should probably have a special case for liquids, since waterlogging exists.

**Comment by JustTalDevelops** [comment] 2022-08-01 05:31
Resolved by commit #9c073874846c61ca50bedcc1509ffec8a1e4e1f1.

**Closed by JustTalDevelops** 2022-08-01 05:31 UTC
Labels: bug
