### ISSUE TITLE
"disconnected from server" when disconnecting a player on join

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#335] opened 2021-11-27 12:53 UTC
![image](https://user-images.githubusercontent.com/45609733/143681982-004d61aa-0e82-47a8-932b-281f0f7e041d.png)
![image](https://user-images.githubusercontent.com/45609733/143682001-8309bb9d-324a-4fe4-8c98-8088c284ed87.png)
This is actually becoming a problem for me, since I had a server in the past and I'm planning on reopening it. Many people still try to connect daily so I want to let them know that we have a discord server and that the server is comming back soon. I have to do some get around to make the message display but most of them either only work if they have a good wifi or just freezes the server randomly.

**Comment by Sandertv** [comment] 2021-11-27 12:55
This is a duplicate of #251.

**Closed** 2021-11-27 12:55 UTC
Labels: bug, duplicate
